# Generated by Django 3.2.8 on 2021-11-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211112_0214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datadiri',
        ),
    ]
